version: '3.8'
services:
  backend:
    container_name: photomong-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    command: npm start            

  admin:
    container_name: photomong-admin
    build: ./admin
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/usr/src/app      

  app:
    container_name: photomong-app
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: npm start
