version: '3.8'
services:
  backend:
    container_name: photomong-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    command: npm start                   
  app:
    container_name: photomong-app
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: npm start
